#-------------------------------
# General Site Settings
title: Pea&Pig
logo: logo.svg # You can add own logo.
description: Pea&Pig are always happy.


#-------------------------------
# Author Settings
author:
  name: Pea&Pig
  say-hello: <center><strong>Pea&Pig</strong></center>
  bio: Pea and Pig are good friends. They are happy every day.